# Generated by Django 3.2.8 on 2022-06-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDetails',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('CourseCode', models.CharField(max_length=10)),
                ('SemesterCode', models.CharField(max_length=50)),
                ('Section', models.IntegerField()),
                ('Description', models.CharField(max_length=200)),
            ],
        ),
    ]
